name: newsletter_app
description: "Application bureau Linux pour envoyer des newsletters personnalisées"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mailer: ^6.1.0
  file_picker: ^8.1.7
  csv: ^6.0.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_widget_from_html_core: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
